name: Automated Tests

on:
  push:
    branches:
      - main

jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run test 1
        run: python find_lowest_number.py test_data/test1_input.txt test_data/output1.txt

      - name: Compare output for test 1
        run: diff -u test_data/output1.txt test_data/test1_expected.txt

  test2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run test 2
        run: python find_lowest_number.py test_data/test2_input.txt test_data/output2.txt

      - name: Compare output for test 2
        run: diff -u test_data/output2.txt test_data/test2_expected.txt

  test3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run test 3
        run: python find_lowest_number.py test_data/test3_input.txt test_data/output3.txt

      - name: Compare output for test 3
        run: diff -u test_data/output3.txt test_data/test3_expected.txt
